springdoc:
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
spring:
  server:
    port: 8080
    servlet:
      context-path: "/${spring.application.api-version}"
  datasource:
    url: jdbc:mysql://localhost:3306/MINENGER-APP?useSSL=false
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
